sudo: required

language: node_js
#node_js:
#- node
#- iojs
#- "6"
#- "4" # debian sid
#- "0.10" # debian stable
# TODO: test those versions instead of the docker node version

services:
- docker

install:
- docker build -t memry .
- mkdir storage
- docker run -d --name memry -p 127.0.0.1:80:8018 -v `pwd`/storage:/storage memry

before_script:
- sudo apt-get -qq update
- sudo apt-get install -y jq

script:
- docker ps | grep -q memry
- ./test.sh curl -sST- http://127.0.0.1
- docker kill memry

- openssl req -nodes -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
- docker run -d --name memry -p 127.0.0.1:80:8018 -v `pwd`/storage:/storage memry --tls-cert cert.pem --tls-key key.pem
- ./test.sh curl -sSkT- https://127.0.0.1
