sudo: required

language: node_js
#node_js:
#- node
#- iojs
#- "6"
#- "4" # debian sid
#- "0.10" # debian stable
# TODO: test those versions instead of the docker node version

services:
- docker

install:
- docker build -t memry .
- mkdir storage
- docker run -d --name memry -p 127.0.0.1:80:8018 -v `pwd`/storage:/storage memry /storage -h 0.0.0.0

before_script:
- sudo apt-get -qq update
- sudo apt-get install -y jq

script:
- docker ps | grep -q memry
- echo "ohai" | curl -sST- http://127.0.0.1 > r.json
- echo "59a6f8a560dc8a7f99f470570bcc100f50e415922fbf71a27af34c5630cf233a  storage/`jq -r .id < r.json`.bin" | sha256sum -c
